-- Setup seguro: NÃO apaga o banco existente
CREATE DATABASE IF NOT EXISTS plataforma_ong CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE plataforma_ong;

-- Tabelas (somente se não existirem)
CREATE TABLE IF NOT EXISTS usuarios (
  id INT AUTO_INCREMENT PRIMARY KEY,
  nome VARCHAR(100) NOT NULL,
  email VARCHAR(150) NOT NULL UNIQUE,
  senha VARCHAR(255) NOT NULL,
  cargo ENUM('admin', 'coordenador', 'professor', 'voluntario') NOT NULL DEFAULT 'voluntario',
  ativo BOOLEAN DEFAULT TRUE,
  ultimo_login DATETIME NULL,
  avatar TEXT NULL,
  telefone VARCHAR(20) NULL,
  data_nascimento DATE NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_email (email),
  INDEX idx_cargo (cargo),
  INDEX idx_ativo (ativo)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS professores (
  id INT AUTO_INCREMENT PRIMARY KEY,
  nome VARCHAR(100) NOT NULL,
  cpf VARCHAR(14) UNIQUE,
  rg VARCHAR(20),
  data_nasc DATE NOT NULL,
  sexo ENUM('M', 'F', 'Outro') NOT NULL,
  email VARCHAR(100) UNIQUE,
  telefone VARCHAR(15),
  endereco VARCHAR(200),
  numero VARCHAR(10),
  complemento VARCHAR(50),
  bairro VARCHAR(100),
  cidade VARCHAR(100),
  estado VARCHAR(2),
  cep VARCHAR(9),
  formacao VARCHAR(200) NOT NULL,
  especializacao TEXT,
  experiencia_anos INT,
  registro_profissional VARCHAR(50),
  salario DECIMAL(10, 2),
  data_admissao DATE NOT NULL DEFAULT (CURRENT_DATE),
  data_demissao DATE NULL,
  status ENUM('ativo', 'inativo', 'licenca', 'ferias') NOT NULL DEFAULT 'ativo',
  carga_horaria_semanal INT,
  observacoes TEXT,
  foto_url VARCHAR(500),
  usuario_id INT NOT NULL,
  ativo BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted_at TIMESTAMP NULL,
  FOREIGN KEY (usuario_id) REFERENCES usuarios(id) ON DELETE CASCADE,
  INDEX idx_cpf (cpf),
  INDEX idx_email (email),
  INDEX idx_status (status),
  INDEX idx_ativo (ativo),
  INDEX idx_usuario (usuario_id)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS cursos (
  id INT AUTO_INCREMENT PRIMARY KEY,
  nome VARCHAR(100) NOT NULL,
  codigo VARCHAR(20) NOT NULL UNIQUE,
  descricao TEXT,
  categoria ENUM('informatica', 'artesanato', 'culinaria', 'idiomas', 'musica', 'esportes', 'reforco_escolar', 'profissionalizante', 'outros') NOT NULL DEFAULT 'outros',
  nivel ENUM('iniciante', 'intermediario', 'avancado') NOT NULL DEFAULT 'iniciante',
  carga_horaria_total INT NOT NULL,
  duracao_meses INT NOT NULL,
  idade_minima INT,
  idade_maxima INT,
  vagas_disponiveis INT NOT NULL,
  vagas_ocupadas INT DEFAULT 0,
  data_inicio DATE NOT NULL,
  data_fim DATE NOT NULL,
  horario_inicio TIME NOT NULL,
  horario_fim TIME NOT NULL,
  dias_semana JSON NOT NULL,
  local VARCHAR(200) NOT NULL,
  sala VARCHAR(50),
  material_necessario TEXT,
  pre_requisitos TEXT,
  objetivos TEXT,
  metodologia TEXT,
  avaliacao TEXT,
  certificado BOOLEAN DEFAULT TRUE,
  valor_curso DECIMAL(10, 2) DEFAULT 0.00,
  gratuito BOOLEAN DEFAULT TRUE,
  status ENUM('planejado', 'inscricoes_abertas', 'em_andamento', 'concluido', 'cancelado', 'suspenso') NOT NULL DEFAULT 'planejado',
  professor_id INT NOT NULL,
  usuario_id INT NOT NULL,
  observacoes TEXT,
  foto_url VARCHAR(500),
  ativo BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted_at TIMESTAMP NULL,
  FOREIGN KEY (professor_id) REFERENCES professores(id) ON DELETE CASCADE,
  FOREIGN KEY (usuario_id) REFERENCES usuarios(id) ON DELETE CASCADE,
  INDEX idx_codigo (codigo),
  INDEX idx_categoria (categoria),
  INDEX idx_status (status),
  INDEX idx_professor (professor_id),
  INDEX idx_data_inicio (data_inicio),
  INDEX idx_ativo (ativo)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS alunos (
  id INT AUTO_INCREMENT PRIMARY KEY,
  nome VARCHAR(100) NOT NULL,
  data_nasc DATE NOT NULL,
  cpf VARCHAR(14) UNIQUE,
  rg VARCHAR(20),
  sexo ENUM('M', 'F', 'Outro') NOT NULL,
  telefone VARCHAR(20),
  email VARCHAR(150),
  endereco VARCHAR(200),
  numero VARCHAR(10),
  complemento VARCHAR(100),
  bairro VARCHAR(100),
  cidade VARCHAR(100),
  estado VARCHAR(2),
  cep VARCHAR(10),
  nome_responsavel VARCHAR(100),
  cpf_responsavel VARCHAR(14),
  telefone_responsavel VARCHAR(20),
  email_responsavel VARCHAR(150),
  parentesco VARCHAR(50),
  turma VARCHAR(50),
  serie VARCHAR(20),
  escola VARCHAR(150),
  restricao_alimentar TEXT,
  medicamentos TEXT,
  observacoes_medicas TEXT,
  ativo BOOLEAN DEFAULT TRUE,
  data_matricula DATE NOT NULL DEFAULT (CURRENT_DATE),
  numero_matricula VARCHAR(20) UNIQUE,
  foto TEXT,
  documentos JSON DEFAULT ('[]'),
  usuario_id INT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (usuario_id) REFERENCES usuarios(id) ON DELETE SET NULL,
  INDEX idx_cpf (cpf),
  INDEX idx_numero_matricula (numero_matricula),
  INDEX idx_ativo (ativo),
  INDEX idx_data_matricula (data_matricula)
) ENGINE=InnoDB;
